#!/bin/sh

# Check if we need to send notification
[ "$(playerctl status)" != "Playing" ] && exit 0

ARTWORK=$(playerctl metadata mpris:artUrl)
[ "$ARTWORK" == "$(cat /home/bshtrepi/.cache/spotifyd/albumart/current.txt)" ] && exit 0

# Fetch the album art
echo $ARTWORK > /home/bshtrepi/.cache/spotifyd/albumart/current.txt
curl -s $ARTWORK > /home/bshtrepi/.cache/spotifyd/albumart/current.jpg

# Fetch title, artist and album
TITLE=$(playerctl metadata title)
ARTIST=$(playerctl metadata artist)
ALBUM=$(playerctl metadata album)

# Send notification
notify-send \
    -i /home/bshtrepi/.cache/spotifyd/albumart/current.jpg \
    "Now Playing: $TITLE" \
    "By $ARTIST - $ALBUM"
