name: Create release with archives

on:
  pull_request:
    tags:
      - '*'

jobs:
  create_release:
    runs-on: ubuntu-latest
    outputs:
      upload_url: ${{ steps.create_release.outputs.upload_url }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref_name }} 
          release_name: ${{ github.ref_name }}
          draft: false
          prerelease: false

  create_zip:
    runs-on: ubuntu-latest
    needs: create_release
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Create zip archive
        run: zip -r config-files.zip ./*

      - name: Upload zip asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ needs.create_release.outputs.upload_url }} 
          asset_path: ./config-files.zip
          asset_name: config-files.zip
          asset_content_type: application/zip

  create_tar_gz:
    runs-on: ubuntu-latest
    needs: create_release
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Create tar.gz archive
        run: tar -czvf config-files.tar.gz ./*

      - name: Upload tar.gz asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ needs.create_release.outputs.upload_url }} 
          asset_path: ./config-files.tar.gz
          asset_name: config-files.tar.gz
          asset_content_type: application/gzip
